import React, { useEffect, useState } from 'react';
import { Card } from '../components/common/Card';
import { Button } from '../components/common/Button';
import { Badge } from '../components/common/Badge';
import { fetchAdminWithdrawals, approveWithdrawal, rejectWithdrawal, fetchPayouts, createPayout, updatePayout } from '../services/adminService';
import { formatCurrency, formatDate } from '../utils/formatters';
import { useNotification } from '../hooks/useNotification';
export const AdminWithdrawals = () => {
  const [items, setItems] = useState([]); const [payouts, setPayouts] = useState([]); const { showSuccess, showError } = useNotification();
  const load = async () => { try { const [withdrawals, payoutData] = await Promise.all([fetchAdminWithdrawals(), fetchPayouts()]); setItems(withdrawals.items || []); setPayouts(payoutData.items || payoutData || []); } catch (e) { showError(e.message || 'Unable to load financial operations'); } };
  useEffect(() => { load(); }, []);
  const approve = async (id) => { try { await approveWithdrawal(id); showSuccess('Withdrawal approved.'); load(); } catch (e) { showError(e.message || 'Approval failed'); } };
  const reject = async (id) => { if (!window.confirm('Reject request and release the held balance?')) return; try { await rejectWithdrawal(id); showSuccess('Withdrawal rejected and balance released.'); load(); } catch (e) { showError(e.message || 'Rejection failed'); } };
  const payout = async (item) => { try { await createPayout({ withdrawRequestId: item.id, gateway: 'BANK_TRANSFER' }); showSuccess('Payout created.'); load(); } catch (e) { showError(e.message || 'Payout creation failed'); } };
  const transition = async (id, action) => { try { await updatePayout(id, action, action === 'fail' ? { failureReason: 'Marked failed by administrator' } : {}); showSuccess(`Payout ${action} completed.`); load(); } catch (e) { showError(e.message || 'Payout update failed'); } };
  return <div><div className="page-heading"><h1>Withdrawal & Payout Management</h1><p>Review requests and manage bank-transfer payouts.</p></div><Card><h2>Withdrawal requests</h2><div className="admin-withdrawal-list">{items.map((item) => <article className="bank-account-item" key={item.id}><div><strong>{formatCurrency(item.amount)} · {item.withdrawal_number}</strong><p>User: {item.user_id}</p><small>{formatDate(item.created_at)}</small></div><div className="bank-account-actions"><Badge status={item.status}>{item.status}</Badge>{item.status === 'pending' && <><Button onClick={() => approve(item.id)}>Approve</Button><Button onClick={() => reject(item.id)}>Reject</Button></>}{item.status === 'approved' && <Button onClick={() => payout(item)}>Create payout</Button>}</div></article>)}{items.length === 0 && <p className="empty-state">No withdrawal requests found.</p>}</div></Card><Card><h2>Payouts</h2><div className="admin-withdrawal-list">{payouts.map((item) => <article className="bank-account-item" key={item.id}><div><strong>{item.payout_number} · {formatCurrency(item.amount)}</strong><p>{item.gateway} · {item.transaction_reference || 'No transaction reference'}</p><small>{formatDate(item.created_at)}</small></div><div className="bank-account-actions"><Badge status={item.status}>{item.status}</Badge>{item.status === 'PENDING' && <Button onClick={() => transition(item.id, 'process')}>Process</Button>}{item.status === 'PROCESSING' && <Button onClick={() => transition(item.id, 'complete')}>Complete</Button>}{['PENDING','PROCESSING'].includes(item.status) && <Button onClick={() => transition(item.id, 'fail')}>Fail</Button>}</div></article>)}{payouts.length === 0 && <p className="empty-state">No payouts created yet.</p>}</div></Card></div>;
};
